#!/bin/sh

cd `dirname $0`

PIDFILE=chessd.pid
LOGFILE=chessd.log

case "$1" in
  start)
    echo "Starting chessd...."
    twistd --logfile $LOGFILE --pidfile $PIDFILE -r epoll -oy src/chessd.tac
    ;;
  run)
    echo "Running chessd in the foreground...."
    twistd --pidfile $PIDFILE -r epoll -noy src/chessd.tac
    ;;
  test)
    echo "Running test suite...."
    trial -e test/
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  pull)
    echo "Pulling latest changes (but not restarting server)...."
    hg pull
    hg update -C
    ;;
  upgrade)
    echo "Upgrading and restarting server...."
    $0 stop
    hg pull
    hg update -C
    $0 start
    ;;
  reloaddb)
    echo "Reloading database...."
    mysql chess < db/db.sql
    ./scripts/import-eco.py
    ;;
  log)
    echo "Showing chessd log..."
    tail -100 $LOGFILE
    ;;
  profile)
    echo "Running chessd in profile mode...."
    twistd --logfile $LOGFILE --profile profile-chessd.data --savestats --profiler cProfile -r epoll -noy src/chessd.tac
    ;;
  stop)
    if [ -f $PIDFILE ]; then
      echo "Stopping chessd...."
      kill `cat $PIDFILE`
    else
      echo "Chessd does not appear to be running...."
    fi
    ;;
  *)
    echo "Usage: $0 (start|stop|run|test|profile|upgrade|reloaddb|log|restart|pull)"
    ;;
esac

