import re
import bcrypt
import random
import string

from db import db

users = {}

# a registered user
class User:
	def __init__(self, id, name, passwd_hash):
                self.id = id
                self.name = name
                self.passwd_hash = passwd_hash
                self.is_guest = False

        def set_passwd(self, passwd):
                assert(self.id)
                print "salt " + bcrypt.gensalt()
                print "hash " + bcrypt.hashpw(passwd, bcrypt.gensalt())
                self.passwd_hash = bcrypt.hashpw(passwd, bcrypt.gensalt())
                db.query("UPDATE user SET user_passwd='%s' WHERE user_id='%s'" % (self.passwd_hash, self.id))

        # check if an unencrypted password is correct
        def check_passwd(self, passwd):
                # don't perform expensive computation on arbitrarily long data
                if len(passwd) > 32:
                        return False
                return bcrypt.hashpw(password, self.passwd_hash) == self.passwd_hash

class GuestUser:
        def __init__(self, name):
                self.is_guest = True
                if name == None:
                        self.name = 'Guest'
                        for i in range(4):
                                self.name = self.name + random.choice(string.ascii_uppercase)
                        self.autogenerated_name = True
                else:
                        self.name = name
                        self.autogenerated_name = False

class UsernameException(Exception):
        def __init__(self, reason):
                self.reason = reason

def get_by_name(name):
        if name.lower() == 'g' or name.lower() == 'guest':
                return GuestUser(None)
        elif not re.match('^[a-zA-Z_]+$', name):
                raise UsernameException('Sorry, names can only consist of lower and upper case letters.  Try again.')
        elif len(name) < 3:
                raise UsernameException('A name should be at least %d characters long!  Try again.' % 3)
        elif len(name) > 18:
                raise UsernameException("Sorry, names may be at most %d characters long.  Try again." % 18)

        res = db.query("SELECT user_id,user_name,user_passwd FROM user WHERE user_name='%s'" % name)
        row = db.fetch()
        if row:
                return User(row[0], row[1], row[2])
        else:
                return GuestUser(name)

# vim: expandtab tabstop=8 softtabstop=8 shiftwidth=8 smarttab autoindent ft=python
