#!/bin/sh
xgettext --language=Python --output=locale/chessd.pot --from-code=utf-8 src/*.py
for lang in compat es; do
	msginit --no-translator -i locale/chessd.pot -o locale/$lang.po
	#msginit -i locale/chessd.pot -o locale/$lang.po
done

