#!/bin/sh
xgettext --language=Python --keyword=N_ --keyword=write_ --keyword=nwrite_ --keyword=translate --output=locale/chessd.pot --from-code=utf-8 --package-name=FatICS src/*.py src/*/*.py

# for testing:
# %s/msgstr\(.*\(\_.".*"\)*\)/msgstr\U\1/g
# %s/%S/%s/g
# %s/%D/%d/g
# %s/\\N/\\n/g
# %s/%([A-Z]\+)S/\L\0/g
for lang in upper; do
	msginit --no-translator -i locale/chessd.pot -o locale/$lang.po
done

#for lang in compat es; do
#	msginit -i locale/chessd.pot -o locale/$lang.po
#done

