#!/bin/sh

for lang in es compat; do
	msgmerge -U locale/$lang.po locale/chessd.pot
	msgfmt -o locale/$lang/LC_MESSAGES/chessd.mo locale/$lang.po
done

for lang in upper; do
	msgfmt -o locale/$lang/LC_MESSAGES/chessd.mo locale/$lang.po
done

